name: 'Upload VEga API'
description: 'Uploads Api to viewing service'
inputs:
  openSpec:
    description: 'path to open api spec'
    required: true
  apiKey:
    description: 'api-key to viewing server'
    required: true
  authEndPoint:
    description: 'end point of the auth'
    required: true
  server:
    desrciption: 'which server it is'
    required: true

runs:
  using: "composite"
  steps:        
      - name: Edit API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://5d7c-24-19-134-8.ngrok.io/editMasterApi'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"apiKey": "${{ inputs.apiKey }}", "openSpec": ${{ inputs.openSpec }}, "authEndPoint": "${{ inputs.authEndPoint }}", "server": "${{ inputs.server }}"}'

   